development:
  adapter: postgresql
  encoding: unicode
  database: brandish_dev
  pool: 5
  username: brandish
  password: brandish

test:
  adapter: postgresql
  encoding: unicode
  database: brandish_test
  pool: 5
  username: brandish
  password: brandish

production:
  adapter: postgresql
  encoding: unicode
  database: brandish_production
  pool: 5
  username: brandish
  password: brandish
